# This file is auto-generated by build_aimhigh.sh
# DO NOT EDIT MANUALLY

[app]
title = AimHigh
package.name = aimhigh
package.domain = org.aimhigh
source.dir = .
version = 1.0.0
requirements = 
    python3==3.9.13,
    kivy==2.1.0,
    pyjnius==1.4.2,
    cryptography==38.0.1

[buildozer]
log_level = 2
warn_on_root = 1

# Android configuration
android.sdk_path = /home/runner/android-sdk
android.ndk_path = /home/runner/android-sdk/ndk/25.2.9519653
android.ndk_version = 25.2.9519653
android.sdk_version = 34
android.api_level = 33
android.accept_sdk_license = True
android.aidl_path = /home/runner/android-sdk/build-tools/34.0.0/aidl
android.ant_path = /usr/bin/ant

# Permissions
android.permissions = 
    INTERNET,
    CAMERA,
    NFC,
    READ_EXTERNAL_STORAGE

# Build settings
android.arch = armeabi-v7a
p4a.branch = develop
android.debug = 1

# License
license = Apache-2.0
