name: Android APK Builder CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make script executable
      run: chmod +x build_aimhigh.sh

    - name: Run Build Script
      run: ./build_aimhigh.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifacts
        path: |
          $HOME/aimhigh_build/artifacts/*.apk
          $HOME/aimhigh_build/artifacts/build.log
        retention-days: 30
