name: Build APK on GitHub

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK and tools
      run: |
        # Install Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_HOME=$PWD" >> $GITHUB_ENV
        echo "$PWD/cmdline-tools/latest/bin:$PWD/platform-tools" >> $GITHUB_PATH
        
        # Accept licenses and install packages
        yes | ./cmdline-tools/latest/bin/sdkmanager --licenses
        ./cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-33" "ndk;25.2.9519653"

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq \
            git zip unzip python3-pip \
            zlib1g-dev libncurses5-dev \
            liblzma-dev lzma

    - name: Set up Buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
            buildozer==1.5.0 \
            cython==0.29.36 \
            virtualenv==20.24.3

    - name: Configure Buildozer
      run: |
        buildozer init
        cat >> buildozer.spec <<EOL
        # Android specific
        android.sdk_path = $ANDROID_HOME
        android.ndk_path = $ANDROID_HOME/ndk/25.2.9519653
        android.ndk_version = 25.2.9519653
        android.sdk_version = 34
        android.api_level = 33
        android.accept_sdk_license = True
        EOL

    - name: Build APK
      run: |
        set -ex
        buildozer -v android debug
        
        # Verify and copy APK
        mkdir -p artifacts
        if ls bin/*.apk >/dev/null 2>&1; then
          cp bin/*.apk artifacts/
          echo "APK successfully built and copied"
        else
          echo "::error::No APK files found in bin directory"
          ls -la bin/
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifacts
        path: artifacts/*.apk
        if-no-files-found: error
