name: Build APK on GitHub

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android tools
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq \
            git zip unzip python3-pip \
            zlib1g-dev libncurses5-dev \
            liblzma-dev lzma \
            android-sdk-build-tools

        # Install Aidl specifically
        sudo apt-get install -y -qq android-sdk-aidl

    - name: Set up Buildozer
      run: |
        python -m pip install --upgrade pip
        python -m pip install \
            buildozer==1.5.0 \
            cython==0.29.36 \
            virtualenv==20.24.3

    - name: Configure Buildozer
      run: |
        buildozer init
        cat >> buildozer.spec <<EOL
        # Android specific
        android.sdk_path = /usr/lib/android-sdk
        android.ndk_path = /usr/lib/android-ndk
        android.accept_sdk_license = True
        android.ant_path = /usr/bin/ant
        android.aidl_path = /usr/bin/aidl
        EOL

    - name: Build APK with error handling
      run: |
        set -ex
        buildozer -v android debug
        
        # Verify APK exists before copying
        if ls bin/*.apk 1> /dev/null 2>&1; then
          mkdir -p artifacts
          cp bin/*.apk artifacts/
          echo "APK successfully copied"
        else
          echo "::error::No APK files found in bin directory"
          ls -la bin/
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifacts
        path: artifacts/*.apk
        if-no-files-found: error
