name: Android APK Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK
      run: |
        # Install Command Line Tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-*.zip -d $HOME/android-sdk
        mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        
        # Pre-accept licenses
        mkdir -p $HOME/android-sdk/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $HOME/android-sdk/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $HOME/android-sdk/licenses/android-sdk-arm-dbt-license
        
        # Install required components
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install \
            "build-tools;34.0.0" \
            "platform-tools" \
            "platforms;android-33" \
            "ndk;25.2.9519653"

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq \
            git zip unzip python3 python3-pip python3-dev \
            zlib1g-dev libncurses5-dev libssl-dev libffi-dev \
            liblzma-dev lzma ant

    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip wheel
        python3 -m pip install \
            buildozer==1.5.0 \
            cython==0.29.36 \
            virtualenv==20.24.3 \
            setuptools==68.0.0

    - name: Initialize Buildozer
      run: |
        buildozer init
        cat > buildozer.spec <<EOL
title = MyApp
package.name = myapp
package.domain = org.example
source.dir = .
version = 0.1
requirements = python3,kivy==2.1.0

# Android configuration
android.sdk_path = $ANDROID_SDK_ROOT
android.ndk_path = $ANDROID_SDK_ROOT/ndk/25.2.9519653
android.ndk_version = 25.2.9519653
android.sdk_version = 34
android.api_level = 33
android.accept_sdk_license = True
android.aidl_path = $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl
android.ant_path = /usr/bin/ant

# Build settings
android.arch = armeabi-v7a
p4a.branch = develop

# Apache License
license = Apache-2.0
EOL

    - name: Build APK with retries
      run: |
        set -ex
        for attempt in {1..3}; do
          echo "Attempt $attempt/3"
          if buildozer -v android debug; then
            mkdir -p artifacts
            cp bin/*.apk artifacts/
            echo "::notice::Build succeeded on attempt $attempt"
            break
          elif [ $attempt -eq 3 ]; then
            echo "::error::All build attempts failed"
            ls -la bin/
            exit 1
          else
            echo "::warning::Build failed, retrying in 10 seconds..."
            sleep 10
          fi
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifacts
        path: |
          artifacts/*.apk
          buildozer.spec
        retention-days: 30
