- name: Create Release
  uses: softprops/action-gh-release@v1
  if: success()
  with:
    files: artifacts/*.apk
    tag_name: "v$(date +'%Y.%m.%d')"
    name: "AimHigh $(date +'%Y.%m.%d')"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
